### ISSUE TITLE
"Array.prototype.slice: 'this' is null or undefined" error in IE9

### ISSUE THREAD

**Issue by alisnic** [stacktracejs/stack-generator#2]
https://github.com/stacktracejs/stack-generator/blob/a5cd8e06872baa0d6ee88ca9760ca2dde0c54bb0/stack-generator.js#L25

**Comment by oliversalzburg** [comment]
Seems like we need a polyfill version here as well

**Comment by alisnic** [comment]
Wow, thanks for fast response and fix!
